### ISSUE TITLE
Author??

### ISSUE THREAD

**Issue by antonio-pedro99** [augusto-carlos/Nestjs-Postgres-RabbitMQ-JWT-AWS#2]
https://github.com/augusto-carlos/Nestjs-Postgres-RabbitMQ-JWT-AWS/blob/ac557933c60ba108312f5c8eb065846f29b352b2/README.md?plain=1#L67

**Comment by antonio-pedro99** [comment]
@augusto-carlos parece que viste!

**Comment by augusto-carlos** [comment]
Vi sim. Na verdade este README file é gerado automaticamente como start do projecto. Irei fazer outro personalizado. De qualquer, forma muito obrigado!!
